#!/bin/sh
##################################################################################
## Bashish, a console theme engine
## Copyright (C) 2005 Thomas Eriksson
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
########################################################
##
## This is the prompt loader for bashish
##
########################################################
##
## NOTE! Incomplete, buggy and non-POSIX shells may parse
## this file, so no ksh-specific code will be accepted in here
##
######################################################################

PS2='> '
PS3='#? '
PS4='+ '

## load the fallback prompt to memory
case "$SHELLNAME" in
bash)
	PS1='\s-\v\$ '
	unset PROMPT_COMMAND
;;
zsh)
	PS1='%m%# '
	PS2='%_> '
	PS3='?# '
	PS4='+%N:%i> '
	unset RPS1 RPS2
	unset -f precmd preexec
;;
*)
	case '$UID' in
	0) PS1='# ';;
	*) PS1='$ ';;
	esac
esac

unset PROMPTSTR TITLE
