#!/bin/sh
##################################################################################
## Bashish, a console theme engine
## Copyright (C) 2005 Thomas Eriksson
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
##################################################################################
#  detect shellname
##################################################################################
##
## Detectshterm detect which shell is in use.
##
## The variables $SHELLNAME does not affect normal
## applications.
##
######################################################################
##
## NOTE! Incomplete, buggy and non-POSIX shells may parse
## this file, so no ksh-specific code will be accepted in here
##
######################################################################

## if $SHELLNAME is set prior to loading this module
## bashish will not probe shell and use the preset value
test "$SHELLNAME" || {

	## generic sh
	SHELLNAME=sh
	
	## ksh
	test "$SECONDS"&&SHELLNAME=ksh

	## zsh
	test "$ZSH_VERSION"&&SHELLNAME=zsh
	
	## bash
	test "$BASH_VERSION"&&SHELLNAME=bash
}

test "x${TTY}" = x && TTY=$(tty 2>/dev/null)
