#!/bin/sh
##################################################################################
## Bashish, a console theme engine
## Copyright (C) 2005 Thomas Eriksson
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
########################################################
##
## This is the prompt loader for bashish
##
########################################################
##
## NOTE! Incomplete, buggy and non-POSIX shells may parse
## this file, so no ksh-specific code will be accepted in here
##
######################################################################

## prompt setting function, null as default
_bashish_prompt () { :;}


## write the shell PID so "bashishtheme" can force a theme update by
## sending a WINCH, which subsequently makes promptupdate to run
test -d "$HOME/.bashish/tmp/${TTY##*/}" && printf "$$" >$HOME/.bashish/tmp/${TTY##*/}/shpid

## load the fallback prompt to memory
_bashish_promptupdate ()
{
	## temporarily disable CTRL+C
	trap "" INT
	
	## check if the theme is unsynced with the latest theme in 
	## bashishtheme, if so, force a theme update
	test -f "$HOME/.bashish/tmp/${TTY##*/}/sync" || {
		bashish
		hash -r
		printf "\033[0;0r"
	
		## load the fallback prompt to memory
		if test -f "$HOME/.bashish/bt/defaults/prompt.$SHELLNAME"
		then
			. "$HOME/.bashish/bt/defaults/prompt.$SHELLNAME"
		else
			if test -f "$HOME/.bashish/bt/defaults/prompt.ksh"
			then
				. "$HOME/.bashish/bt/defaults/prompt.ksh"
			else
				test -f "$HOME/.bashish/bt/defaults/prompt.sh" && . "$HOME/.bashish/bt/defaults/prompt.sh"
			fi
		fi
	
		test -f "$HOME/.bashish/bt/defaults/prompt.$SHELLNAME" && . "$HOME/.bashish/bt/defaults/prompt.$SHELLNAME"
		
		## load config defaults
		test -f "$HOME/.bashish/bt/prompt/conf.sh" && . "$HOME/.bashish/bt/prompt/conf.sh"
	
	
		## continue loading if prompt is loaded cleanly
		## if not available, try to use 
		if test -f "$HOME/.bashish/bt/prompt/prompt.$SHELLNAME"
		then
			. "$HOME/.bashish/bt/prompt/prompt.$SHELLNAME"
		else
			if test -f "$HOME/.bashish/bt/prompt/prompt.ksh"
			then
				. "$HOME/.bashish/bt/prompt/prompt.ksh"
			else
				test -f "$HOME/.bashish/bt/prompt/prompt.sh" && . "$HOME/.bashish/bt/prompt/prompt.sh"
			fi
		fi
	
		## prompt overrides
		if test -f "$HOME/.bashish/bt/overrides/prompt.$SHELLNAME"
		then
			. "$HOME/.bashish/bt/overrides/prompt.$SHELLNAME"
		else
			if test -f "$HOME/.bashish/bt/overrides/prompt.ksh"
			then
				. "$HOME/.bashish/bt/overrides/prompt.ksh"
			else
				test -f "$HOME/.bashish/bt/overrides/prompt.sh" && . "$HOME/.bashish/bt/overrides/prompt.sh"
			fi
		fi
	
	
		## a small delay makes the term settle down before reloading the prompt
		sleep 0.5
		

	}
	PS2='> '
	PS3='#? '
	PS4='+ '

	## load the fallback prompt to memory
	case "$SHELLNAME" in
	bash)
		PS1='\s-\v\$ '
		unset PROMPT_COMMAND
	;;
	zsh)
		PS1='%m%# '
		PS2='%_> '
		PS3='?# '
		PS4='+%N:%i> '
		unset RPS1 RPS2
		unset -f precmd preexec
	;;
	*)
		case '$UID' in
		0) PS1='# ';;
		*) PS1='$ ';;
		esac
	esac

	## load defaults
	_bashish_defaults
	## load the bashish prompt
	_bashish_prompt

	## load overrides
	_bashish_overrides
	
	## load _bashish_title() if available
	_bashish_title
	
	## re-enable CTRL+C
	trap INT
}

## winch promptupdate
_bashish_winch_promptupdate()
{
	_bashish_promptupdate
	if test "x$BASH" != x
	then
		:
		$PROMPT_COMMAND
	else
		type precmd >/dev/null && precmd
	fi

}

## re-paint on winch signals
if test "x$BASH" != x
then
	trap "PROMPT_COMMAND=\"unset PROMPT_COMMAND;_bashish_promptupdate\"" WINCH
elif test "x$ZSH_NAME" != x
then
	trap "echo \"precmd () { unset -f precmd; _bashish_promptupdate;}" WINCH	
fi

## re-paint whenever changing directory
case "$SHELLNAME" in
ksh)
cd ()
{
	unset -f cd
	cd "$@"
	_bashish_promptupdate
	cd ()
	{
		unset -f cd
		cd "$@"
		_bashish_promptupdate
	}
}
;;
bash|zsh)
cd ()
{
	builtin cd "$@"
	_bashish_promptupdate
}
;;
sh)
## sh does not support 'builtin'
cd ()
{
	chdir ${1+"$@"}
	_bashish_promptupdate
}

## posh does not support 'chdir'
type type 1>/dev/null 2>/dev/null || cd ()
{
	builtin cd "$@"
	_bashish_promptupdate
}

esac


## Normal theme initialization by sending a WINCH signal
kill -s WINCH $$
