#!/bin/sh
##################################################################################
## Bashish, a console theme engine
## Copyright (C) 2005 Thomas Eriksson
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
########################################################
##
## This is the prompt loader for bashish
##
########################################################
##
## NOTE! Incomplete, buggy and non-POSIX shells may parse
## this file, so no ksh-specific code will be accepted in here
##
######################################################################

## prompt setting function, null as default
_bashish_prompt () { :;}

## yay for ksh!
case "$SHELLNAME" in
ksh)
cd ()
{
	unset -f cd
	cd "$@"
	_bashish_prompt
	cd ()
	{
		unset -f cd
		cd "$@"
		_bashish_prompt
	}
}
;;
bash|zsh)
cd ()
{
	builtin cd "$@"
	_bashish_prompt
}
;;
sh)
## sh does not support 'builtin'
cd ()
{
	chdir ${1+"$@"}
	_bashish_prompt
}

## posh does not support 'chdir'
type type 1>/dev/null 2>/dev/null || cd ()
{
	builtin cd "$@"
	_bashish_prompt
}

esac

## Normal theme initialization by sending a WINCH signal
kill -s WINCH $$
