#!/bin/bash
##################################################################################
## Bashish, a console theme engine
## Copyright (C) 2010 Thomas Eriksson
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
##
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
##################################################################################
##
## _bashish_prompt_rcs displays a branch name for various revision control systems
## 
## if a directory is under control of multiple rcs systems, the first one will be
## displayed in this order:
##
## git
## hg
## bzr
## svn
## cvs
##
##################################################################################
_bashish_prompt_rcs_traverse ()
{
	test "x${1}" = x && return 0

	if test -d "${1}/.hg"
	then
		hg branch 2>/dev/null
	elif test -d "${1}/.bzr"
	then
		printf "${1##*/}:$(bzr revno 2>/dev/null)"
	else
		_bashish_prompt_rcs_traverse "${1%/*}"
	fi
}

_bashish_prompt_rcs ()
{
	## use the original __git_ps1 and check for a git-dir
	typeset -f __git_ps1 1>/dev/null 2>/dev/null || . "$BASHISHDIR"/lib/__git_ps1
	typeset GIT_PS1=$(__git_ps1 %s 2>/dev/null)
	test x"${GIT_PS1}" != x && { printf "${GIT_PS1}"; return 0; }
	
	## hg and bzr detection
	typeset HGBZR_PS1=$(_bashish_prompt_rcs_traverse "${PWD}")
	test x"${HGBZR_PS1}" != x && { printf "${HGBZR_PS1}"; return 0; }

	## svn detection
	if test -d .svn
	then
		typeset IFS="
"
		typeset LINE
		for LINE in $(svn info 2>/dev/null)
		do
			case "${LINE}" in
			"URL: "*) typeset SVN_URL="${LINE#URL: }";;
			"Repository Root: "*) typeset SVN_ROOT="${LINE#Repository Root: }";;
			"Revision: "*) typeset SVN_REV="${LINE#Revision: }"
			esac
		done
		unset IFS
		eval typeset SVN_PS1="\"\${SVN_URL#${SVN_ROOT}/}\""
		test x"${SVN_PS1%%/*}" != x && { printf "${SVN_PS1%%/*}:${SVN_REV}"; return 0; }
	fi
	
	## cvs detection
	if test -f CVS/Repository
	then
		CVS_PS1="$(cat CVS/Repository)"
		test x"${CVS_PS1%%/*}" != x && { printf "${CVS_PS1%%/*}"; return 0;}
	fi
	return 0
}

test x$BASHISH_FNLOAD != x1 && _bashish_prompt_rcs "$@"
