#!/bin/bash
##################################################################################
##
## notice: you must open this file with UTF-8 encoding, elsewise it will be truncated
##
##################################################################################
##################################################################################
## Bashish, a console theme engine
## Copyright (C) 2010 Thomas Eriksson
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
##
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
##################################################################################
##
## _bashish_prompt_shellvars is a prompt helper
##
## it prints some helpful variables for prompts, currently
## ESC - escape
## EMBED - begin printing of terminal control characters within a prompt which would not be used for prompt length calculation
## UNEMBED - end a terminal control character statement
## 
## the variables are local for the prompt and will not mess up local variables
##
##################################################################################

test "x$SHELLNAME" = x && SHELLNAME="$1"

## null function (to prevent accidental fork bombs)
## call this function with eval $(_bashish_prompt_shellvars)
case "$SHELLNAME" in
zsh)
function _bashish_prompt_shellvars
{
	printf "typeset _typeset=typeset BEL=\"\007\" ESC=\"\033\" EMBED=\"%%{\" UNEMBED=\"%%}\" TIME=\"%%*\"\n"
}
;;
bash)
function _bashish_prompt_shellvars
{

	printf "typeset _typeset=typeset BEL=\"\007\" ESC=\"\033\" EMBED=\"\\\\[\" UNEMBED=\"\\\\]\" DATE=\"\\\\d\" TIME=\"\\\\t\"\n"
}
;;
ksh)
function _bashish_prompt_shellvars
{
	printf "typeset _typeset=typeset BEL=\"\007\" ESC=\"\033\" EMBED=\"\" UNEMBED=\"\" TIME=\`date +\"%%R:%%S\"\n"
}
;;
sh|*)
function _bashish_prompt_shellvars
{
	printf "_typeset=\"\";BEL=\"\007\";ESC=\"\033\";EMBED=\"\";UNEMBED=\";TIME=\`date +\"%%R:%%S\"\`\"\n"
}
esac		


test x$BASHISH_FNLOAD != x1 && _bashish_prompt_shellvars "$@"
