#!/bin/bash
##################################################################################
## Bashish, a console theme engine
## Copyright (C) 2010 Thomas Eriksson
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
##
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
##################################################################################
##
## _bashish_prompt_shellvars is a prompt helper
##
## it prints some helpful variables for prompts, currently
## ESC - escape
## EMBED - begin printing of terminal control characters within a prompt which would not be used for prompt length calculation
## UNEMBED - end a terminal control character statement
## 
## the variables are local for the prompt and will not mess up local variables
##
##################################################################################

test "x$SHELLNAME" = x && SHELLNAME="$1"

## null function (to prevent accidental fork bombs)
## call this function with eval $(_bashish_prompt_shellvars)
function _bashish_prompt_shellvars_common
{
	## dull otherwise changes color in linux console
	case "$TERM" in
	linux) printf ' DULL=0 BRIGHTBG=1\\;4 =BRIGHTFG=1\\;3';;
	*) printf " BRIGHTBG=10 BRIGHTFG=9";;
	esac
	## OS X Terminal.app (tiger, OSX 10.4) does not handle bold attribute as everybody else
	## bold is set to a slightly darker color than normal (wheres on almost all other terminals
	## it's the opposite)
	## also, bold in combination with bright color makes the text darker, not brighter
	##
	## fix this by using an unassigned color attribute (6), seems to do nothing on Terminal.app
	## for FG to differ from BRIGHTFG we also need to use BOLD attribute to make it more dull
	## however, then we need to check BRIGHTFG so the BOLD attribute isn't set
	##
	## tiger version:
	## TERM_PROGRAM_VERSION=133-1
	##
	## leopard version:
	## TERM_PROGRAM_VERSION=240.2
	##
	## snow leopard version:
	## TERM_PROGRAM_VERSION=272
	case "$TERM_PROGRAM" in
	"Apple_Terminal") printf " DULL=1 BOLD=6 FG="'1\\;3';;
	*) printf " DULL=2 BOLD=1 FG=3";;
	esac
	
	printf " BLACK=0 RED=0 GREEN=2 YELLOW=3 BLUE=4 MAGENTA=5 CYAN=6 WHITE=7	SETCOLOR=m SETSCROLLREG=r SETCURPOS=H NORMAL=0 BG=4 STORECUR=7 RESTORECUR=8 ERASETOEOL=K CURBACK=D CURFWD=C CURUP=A CURDOWN=B BEL=\"\007\" ESC=\"\033\"\n"
}
case "$SHELLNAME" in
tcsh)
function _bashish_prompt_shellvars
{
	printf "set EMBED=\"%%{\" UNEMBED=\"%%}\" TIME=\"%%*\" DATE=%%D"
	_bashish_prompt_shellvars_common
}
;;
csh)
function _bashish_prompt_shellvars
{
	printf "set EMBED=\"\" UNEMBED=\"\" TIME=\"%%*\" DATE=%%D"
	_bashish_prompt_shellvars_common
}
;;
zsh)
function _bashish_prompt_shellvars
{
	printf "local EMBED=\"%%{\" UNEMBED=\"%%}\" TIME=\"%%*\" DATE=%%D"
	_bashish_prompt_shellvars_common
}
;;
bash)
function _bashish_prompt_shellvars
{

	printf "local EMBED=\"\\\\[\" UNEMBED=\"\\\\]\" DATE=\"\\\\d\" TIME=\"\\\\t\""
	_bashish_prompt_shellvars_common
}
;;
ksh)
function _bashish_prompt_shellvars
{
	## all shells but ksh have "local", but dash does not have "typeset" or alias, hence local is preferred to use
	printf "alias local=typeset; typeset EMBED=\"\" UNEMBED=\"\" TIME=\`date +\"%%R:%%S\""
	_bashish_prompt_shellvars_common
}
;;
sh|*)
function _bashish_prompt_shellvars
{
	printf "local EMBED=\"\" UNEMBED=\" TIME=\`date +\"%%R:%%S\"\`\""
	_bashish_prompt_shellvars_common
}
esac		


test x$BASHISH_FNLOAD != x1 && _bashish_prompt_shellvars "$@"
