#!/bin/sh
##################################################################################
## Bashish, a console theme engine
## Copyright (C) 2005 Thomas Eriksson
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
########################################################
##
## This is the prompt loader for bashish
##
########################################################
##
## NOTE! Incomplete, buggy and non-POSIX shells may parse
## this file, so no ksh-specific code will be accepted in here
##
######################################################################

## if the terminal interprets titles (most do: ie xterm, some not, ie linux
## console) this string should not print out on
## the screen, and thus the terminal would not report the cursor being moved
printf "\033]0;title\007\033[6n"

i=0
until test "$i" = 9
do
	CHAR=""
	read -t1 -n1 CHAR
	case "$CHAR" in
	|[|[0-9]|\;) CURPOS="$CURPOS$CHAR";let i++;;
	R)CURPOS="$CURPOS$CHAR";break;;
	esac
done
## clear terminal response
printf "\[A[20D                    [20D[0m" >/dev/tty

_bashish_title() { :;}
case "$CURPOS" in
*";1R")
	exit 0
;;
esac
exit 1
