#!/bin/sh
##############################
##
## Ni!
##
##############################

case `echo -n` in
-n) NI="";;
"") NI=-n;;
esac

echo $NI "\
#!$1
BASHISHDIR=\"$2\"
BASHISH_SHELL=\"$1\"
"
case "$1" in
*zsh*)
echo $NI "emulate -L ksh
"
esac

