#!/bin/sh
##############################
##
## Ni!
##
##############################

case `echo -n` in
-n) NI="";;
"") NI=-n;;
esac

echo $NI "\
#!/bin/bash
BASHISHDIR=\"$2\"
BASHISH_SHELL=\"/bin/bash\"
"

