#!/bin/bash
rm -rf dist
rm -f man/bashish.1
rm -f bin/bashish

for DELETE_FILE in $(find . -type f |grep "~"); do rm "$DELETE_FILE";done

./autogen.sh --prefix=$HOME/Unix
bash ./mkdist
bash ./mkrpm
bash ./mkdeb 
bash ./mkslack
cd dist
md5sum * >MD5SUMS
