#!/bin/sh
## @(#) created by arne
#######################
BASHISH_THEME=bluesteel

_bashish_theme_bluesteel ()
{
THEME_AUTHOR="arne <arne@users.sourceforge.net>"
_bashish_theme_defaults_cp437font

TITLE="$USER @ ${HOSTNAME%%.*}"

BGCOLOR="#000000"
FGCOLOR="#cccccc"
BGBRIGHTNESS="#000000"

}
