#!/bin/sh
##################################################################################
## Bashish, a console theme engine
## Copyright (C) 2005 Thomas Eriksson
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
##################################################################################
##
## THIS IS BASHISH2. YOU WILL BE ASSIMILATED
##
######################################################

## _bashish_module is a function that reads and executes shell script modules
_bashish_module ()
{
	. $BASHISHDIR/main/prompt/sh/$1
}


## cygwin specific fixes
_bashish_module sys/cygwin

## detect shell and terminal
_bashish_module sys/detectsh

## load prompt helpers
_bashish_module sys/loadhelpers

## load the theme engine
_bashish_module sys/loadprompt

## lets the user configure title and prompt strings in themes
_bashish_module sys/userstrings
