#!/bin/bash
#############################################################
##
## These are the fallback values when a theme does not specify
## a theme variable.
##
## It's perfectly ok to mock around and change values here
##
## the same variables as in the bashish themes are supported.
##
## To override the 'theme' variables change the 
## bt/override/theme file
##
#############################################################
##
## Changes take effect at restart or after 'brefresh' has been run
##
#############################################################

test "$TERMNAME" != xterm-xterm && function _bashish_theme_defaults_xterm { :;}


## this function is only run upon startup
function _bashish_theme_defaults_firstrun
{
	SIZE_X=100
	SIZE_Y=40
	function _bashish_theme_defaults_firstrun { :;}
}

## null function if term is UTF-8
function _bashish_theme_defaults_cp437font { :;}

## set the terminal in DOS charset mode (CP437)
test "x$BASHISH_UTF" = x0 && function _bashish_theme_defaults_cp437font
{
	case "${BASHISH_ARGV[0]}" in
	"") 
		## Font to use if the terminal is not in UTF-8 mode and the prompt
		## use CP437 characters
	
		## smoothansi by artwiz: http://artwizaleczapka.sourceforge.net/
		XFONT="-artwiz-smoothansi-medium-r-normal--13-130-75-75-m-60-iso8859-1"
	
		## ASCII.ttf from http://www.apollosoft.de/ASCII/indexen.htm
		FONTNAME="New"
	
		## set PC charset for linux
		test "$TERMNAME" = linux && printf "\033[11m"
	;;
	*)
		## set regular charset for linux
		test "$TERMNAME" = linux && printf "\033[10m"
	esac
}

function _bashish_theme_defaults
{

## run only at startup
_bashish_theme_defaults_firstrun

## clear prompt_command
unset PROMPT_COMMAND

## just a default value
BGCOLOR="#000000"
FGCOLOR="#cccccc"

## as regular terminals *should* be ;)
AFGCOLOR=white
ABGCOLOR=black
FGMOUSECOLOR="#cccccc"
BGMOUSECOLOR="#000000"

## will be set in bt/override/theme
FGCURSORCOLOR=""
BGCURSORCOLOR=""
BOLDCOLOR=""
UNDERLINECOLOR=""

## no shade
BGSHADE=0

## don't enable viewport (overrides transparency)
BGVIEWPORT=0

## don't enable transparency
BGTRANSPARENCY=0

IMAGEFILE=""

## default to $TERM variable as title and icon
case "$TERMNAME" in
cmdtool) TITLE="cmdtool - $SHELL";;
gnome-terminal|konsole|xterm-dtterm) TITLE=Terminal;;
*) TITLE=$TERM;;
esac

## nullify $ICON and $PROMPT, otherwise, strange things may happen...
unset ICON

## the standard XTerm font as default
XFONT="fixed"

## use the Vera font as default scalable font
FONTNAME="Bitstream Vera Sans Mono"

## use 12pt as default size for truetype fonts
FONTSIZE=12

## Anti-alias is quite slow on urxvt, disable by commenting the following line:
URXVTANTIALIAS=1

## the snuffy vga font for the linux console
CFONT=default8x16.psf.gz

## the nufty herring icon
EICON=gnome-terminal.png

## terminal colors
_bashish_theme_defaults_ansi_tango

#_bashish_theme_defaults_ansi_ansilove
}

function _bashish_theme_defaults_ansi_mandrake
{

## these are the ansi colors
## they are less saturated than the regular ansi colors
## most ones taken from Mandrakes Eterm colors
## 
# black
COLOR[0]="#000000"
# red
COLOR[1]="#9e1828"
# green
COLOR[2]="#749A53"
# yellow
COLOR[3]="#C6BF63"
# blue
COLOR[4]="#414171"
# magenta
COLOR[5]="#724D65"
# cyan
COLOR[6]="#4B18179"
# white
COLOR[7]="#ffffff"
# bright black
COLOR[8]="#666666"
# bright red
COLOR[9]="#cf6171"
# bright green
COLOR[10]="#c5f779"
# bright yellow
COLOR[11]="#fff796"
# bright blue
COLOR[12]="#4186be"
# bright magenta
COLOR[13]="#cf9ebe"
# bright cyan
COLOR[14]="#71bebe"
# bright white
COLOR[15]="#ffffff"
}

function _bashish_theme_defaults_ansi_ansilove
{

## ansi colors taken from ansilove http://ansilove.sourceforge.net/
## most ones taken from Mandrakes Eterm colors
# black
COLOR[0]="#000000"
# red
COLOR[1]="#a80000"
# green
COLOR[2]="#00a800"
# yellow
COLOR[3]="#a85400"
# blue
COLOR[4]="#0000a8"
# magenta
COLOR[5]="#a800a8"
# cyan
COLOR[6]="#00a8a8"
# white
COLOR[7]="#a8a8a8"
# bright black
COLOR[8]="#545454"
# bright red
COLOR[9]="#fc5454"
# bright green
COLOR[10]="#54fc54"
# bright yellow
COLOR[11]="#fcfc54"
# bright blue
COLOR[12]="#5454fc"
# bright magenta
COLOR[13]="#fc54fc"
# bright cyan
COLOR[14]="#54fcfc"
# bright white
COLOR[15]="#ffffff"
}

function _bashish_theme_defaults_ansi_tango
{

## ansi colors taken from the tango! project http://www.tango-project.org/
# Cyan colors have been approximized to have a tango-ish saturation

COLOR[0]="#000000"
# red
COLOR[1]="#CC0000"
# green
COLOR[2]="#4E9A06"
# yellow
COLOR[3]="#C4A000"
# blue
COLOR[4]="#3465A4"
# magenta
COLOR[5]="#75507B"
# cyan
COLOR[6]="#277B79"
# white
COLOR[7]="#D3D7CF"
# bright black
COLOR[8]="#555753"
# bright red
COLOR[9]="#EF2929"
# bright green
COLOR[10]="#8AE234"
# bright yellow
COLOR[11]="#FCE94F"
# bright blue
COLOR[12]="#729FCF"
# bright magenta
COLOR[13]="#AD7FA8"
# bright cyan
COLOR[14]="#39B3AF"
# bright white
COLOR[15]="#ffffff"
}

function _bashish_theme_defaults_xterm
{
COLOR[16]="#000000"
COLOR[17]="#00005f"
COLOR[18]="#000087"
COLOR[19]="#0000af"
COLOR[20]="#0000d7"
COLOR[21]="#0000ff"
COLOR[22]="#005f00"
COLOR[23]="#005f5f"
COLOR[24]="#005f87"
COLOR[25]="#005faf"
COLOR[26]="#005fd7"
COLOR[27]="#005fff"
COLOR[28]="#008700"
COLOR[29]="#00875f"
COLOR[30]="#008787"
COLOR[31]="#0087af"
COLOR[32]="#0087d7"
COLOR[33]="#0087ff"
COLOR[34]="#00af00"
COLOR[35]="#00af5f"
COLOR[36]="#00af87"
COLOR[37]="#00afaf"
COLOR[38]="#00afd7"
COLOR[39]="#00afff"
COLOR[40]="#00d700"
COLOR[41]="#00d75f"
COLOR[42]="#00d787"
COLOR[43]="#00d7af"
COLOR[44]="#00d7d7"
COLOR[45]="#00d7ff"
COLOR[46]="#00ff00"
COLOR[47]="#00ff5f"
COLOR[48]="#00ff87"
COLOR[49]="#00ffaf"
COLOR[50]="#00ffd7"
COLOR[51]="#00ffff"
COLOR[52]="#5f0000"
COLOR[53]="#5f005f"
COLOR[54]="#5f0087"
COLOR[55]="#5f00af"
COLOR[56]="#5f00d7"
COLOR[57]="#5f00ff"
COLOR[58]="#5f5f00"
COLOR[59]="#5f5f5f"
COLOR[60]="#5f5f87"
COLOR[61]="#5f5faf"
COLOR[62]="#5f5fd7"
COLOR[63]="#5f5fff"
COLOR[64]="#5f8700"
COLOR[65]="#5f875f"
COLOR[66]="#5f8787"
COLOR[67]="#5f87af"
COLOR[68]="#5f87d7"
COLOR[69]="#5f87ff"
COLOR[70]="#5faf00"
COLOR[71]="#5faf5f"
COLOR[72]="#5faf87"
COLOR[73]="#5fafaf"
COLOR[74]="#5fafd7"
COLOR[75]="#5fafff"
COLOR[76]="#5fd700"
COLOR[77]="#5fd75f"
COLOR[78]="#5fd787"
COLOR[79]="#5fd7af"
COLOR[80]="#5fd7d7"
COLOR[81]="#5fd7ff"
COLOR[82]="#5fff00"
COLOR[83]="#5fff5f"
COLOR[84]="#5fff87"
COLOR[85]="#5fffaf"
COLOR[86]="#5fffd7"
COLOR[87]="#5fffff"
COLOR[88]="#870000"
COLOR[89]="#87005f"
COLOR[90]="#870087"
COLOR[91]="#8700af"
COLOR[92]="#8700d7"
COLOR[93]="#8700ff"
COLOR[94]="#875f00"
COLOR[95]="#875f5f"
COLOR[96]="#875f87"
COLOR[97]="#875faf"
COLOR[98]="#875fd7"
COLOR[99]="#875fff"
COLOR[100]="#878700"
COLOR[101]="#87875f"
COLOR[102]="#878787"
COLOR[103]="#8787af"
COLOR[104]="#8787d7"
COLOR[105]="#8787ff"
COLOR[106]="#87af00"
COLOR[107]="#87af5f"
COLOR[108]="#87af87"
COLOR[109]="#87afaf"
COLOR[110]="#87afd7"
COLOR[111]="#87afff"
COLOR[112]="#87d700"
COLOR[113]="#87d75f"
COLOR[114]="#87d787"
COLOR[115]="#87d7af"
COLOR[116]="#87d7d7"
COLOR[117]="#87d7ff"
COLOR[118]="#87ff00"
COLOR[119]="#87ff5f"
COLOR[120]="#87ff87"
COLOR[121]="#87ffaf"
COLOR[122]="#87ffd7"
COLOR[123]="#87ffff"
COLOR[124]="#af0000"
COLOR[125]="#af005f"
COLOR[126]="#af0087"
COLOR[127]="#af00af"
COLOR[128]="#af00d7"
COLOR[129]="#af00ff"
COLOR[130]="#af5f00"
COLOR[131]="#af5f5f"
COLOR[132]="#af5f87"
COLOR[133]="#af5faf"
COLOR[134]="#af5fd7"
COLOR[135]="#af5fff"
COLOR[136]="#af8700"
COLOR[137]="#af875f"
COLOR[138]="#af8787"
COLOR[139]="#af87af"
COLOR[140]="#af87d7"
COLOR[141]="#af87ff"
COLOR[142]="#afaf00"
COLOR[143]="#afaf5f"
COLOR[144]="#afaf87"
COLOR[145]="#afafaf"
COLOR[146]="#afafd7"
COLOR[147]="#afafff"
COLOR[148]="#afd700"
COLOR[149]="#afd75f"
COLOR[150]="#afd787"
COLOR[151]="#afd7af"
COLOR[152]="#afd7d7"
COLOR[153]="#afd7ff"
COLOR[154]="#afff00"
COLOR[155]="#afff5f"
COLOR[156]="#afff87"
COLOR[157]="#afffaf"
COLOR[158]="#afffd7"
COLOR[159]="#afffff"
COLOR[160]="#d70000"
COLOR[161]="#d7005f"
COLOR[162]="#d70087"
COLOR[163]="#d700af"
COLOR[164]="#d700d7"
COLOR[165]="#d700ff"
COLOR[166]="#d75f00"
COLOR[167]="#d75f5f"
COLOR[168]="#d75f87"
COLOR[169]="#d75faf"
COLOR[170]="#d75fd7"
COLOR[171]="#d75fff"
COLOR[172]="#d78700"
COLOR[173]="#d7875f"
COLOR[174]="#d78787"
COLOR[175]="#d787af"
COLOR[176]="#d787d7"
COLOR[177]="#d787ff"
COLOR[178]="#d7af00"
COLOR[179]="#d7af5f"
COLOR[180]="#d7af87"
COLOR[181]="#d7afaf"
COLOR[182]="#d7afd7"
COLOR[183]="#d7afff"
COLOR[184]="#d7d700"
COLOR[185]="#d7d75f"
COLOR[186]="#d7d787"
COLOR[187]="#d7d7af"
COLOR[188]="#d7d7d7"
COLOR[189]="#d7d7ff"
COLOR[190]="#d7ff00"
COLOR[191]="#d7ff5f"
COLOR[192]="#d7ff87"
COLOR[193]="#d7ffaf"
COLOR[194]="#d7ffd7"
COLOR[195]="#d7ffff"
COLOR[196]="#ff0000"
COLOR[197]="#ff005f"
COLOR[198]="#ff0087"
COLOR[199]="#ff00af"
COLOR[200]="#ff00d7"
COLOR[201]="#ff00ff"
COLOR[202]="#ff5f00"
COLOR[203]="#ff5f5f"
COLOR[204]="#ff5f87"
COLOR[205]="#ff5faf"
COLOR[206]="#ff5fd7"
COLOR[207]="#ff5fff"
COLOR[208]="#ff8700"
COLOR[209]="#ff875f"
COLOR[210]="#ff8787"
COLOR[211]="#ff87af"
COLOR[212]="#ff87d7"
COLOR[213]="#ff87ff"
COLOR[214]="#ffaf00"
COLOR[215]="#ffaf5f"
COLOR[216]="#ffaf87"
COLOR[217]="#ffafaf"
COLOR[218]="#ffafd7"
COLOR[219]="#ffafff"
COLOR[220]="#ffd700"
COLOR[221]="#ffd75f"
COLOR[222]="#ffd787"
COLOR[223]="#ffd7af"
COLOR[224]="#ffd7d7"
COLOR[225]="#ffd7ff"
COLOR[226]="#ffff00"
COLOR[227]="#ffff5f"
COLOR[228]="#ffff87"
COLOR[229]="#ffffaf"
COLOR[230]="#ffffd7"
COLOR[231]="#ffffff"
COLOR[232]="#080808"
COLOR[233]="#121212"
COLOR[234]="#1c1c1c"
COLOR[235]="#262626"
COLOR[236]="#303030"
COLOR[237]="#3a3a3a"
COLOR[238]="#444444"
COLOR[239]="#4e4e4e"
COLOR[240]="#585858"
COLOR[241]="#626262"
COLOR[242]="#6c6c6c"
COLOR[243]="#767676"
COLOR[244]="#808080"
COLOR[245]="#8a8a8a"
COLOR[246]="#949494"
COLOR[247]="#9e9e9e"
COLOR[248]="#a8a8a8"
COLOR[249]="#b2b2b2"
COLOR[250]="#bcbcbc"
COLOR[251]="#c6c6c6"
COLOR[252]="#d0d0d0"
COLOR[253]="#dadada"
COLOR[254]="#e4e4e4"
COLOR[255]="#eeeeee"
}


