#!/bin/bash
###############################################################################
## this module displays theme information
###############################################################################

( 
	## load locale
	_bashish_module sys/locale
	
	## load prompt
	_bashish_prompt_theme
	
	## if possible, clear the screen prior to displaying theme info
	clear 2>/dev/null
	
	## if the theme doesn't contain a theme name
	## get the hardcoded name loadtheme gave it
	test "$THEME_NAME" || THEME_NAME=$BASHISH_THEME
	
	## the theme info
	echo "\

 BASHISH - the good stuff. 
.________________________ ___ __  _      _
|"
## if avaliable show some information about the author
test -n "$THEME_NAME" &&printf "$LOCALE_CT_1_THEME$THEME_NAME$LOCALE_CT_2_THEME"
test -n "$THEME_AUTHOR"&&printf "$LOCALE_CT_1_AUTHOR$THEME_AUTHOR$LOCALE_CT_2_AUTHOR"
test -n "$THEME_VERSION"&&printf "$LOCALE_CT_1_VERSION$THEME_VERSION$LOCALE_CT_2_VERSION"
test -n "$THEME_MADEWITH"&&printf "$LOCALE$LOCALE_CT_1_MADEWITH$THEME_MADEWITH$LOCALE_CT_2_MADEWITH"
test -n "$THEME_URL"&&printf "$LOCALE_CT_1_URL$THEME_URL$LOCALE_CT_2_URL"
test -n "$THEME_COMMENT"&&printf "$LOCALE_CT_1_COMMENT$THEME_COMMENT$LOCALE_CT_2_COMMENT"
printf "		 
!________________________ ___ __  _      _
	
	"
)
