#!/bin/bash
########################################################
##
## This is the theme loader for bashish
##
########################################################

## dummy default theme options
_bashish_theme_defaults () { :;}

## dummy prompt theme
_bashish_theme_prompt () { :;}

## dummy prompt overrides
_bashish_theme_overrides () { :;}
	
## load the theme defaults to memory
test -f "$HOME"/.bashish/defaults/theme && . "$HOME"/.bashish/defaults/theme

typeset BASHISH_THEME

## load the prompt theme to memory
test -f "$HOME"/.bashish/prompt/theme && . "${HOME}"/.bashish/prompt/theme

## test if the loaded theme is a valid bashish2 theme, elsewise it will not 
## be loaded
test "x$BASHISH_THEME" != x &&{
	## this creates the function _bashish_theme_prompt() which calls
	## the selected bashish theme function (very fast)
	eval "function _bashish_theme_prompt { _bashish_theme_$BASHISH_THEME;}"
}
## load the theme overrides to memory
test -f "$HOME"/.bashish/overrides/theme && . "${HOME}"/.bashish/overrides/theme

