#!/bin/bash
##################################################################################
## Bashish, a console theme engine
## Copyright (C) 2005 Thomas Eriksson
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
##################################################################################

typeset BASHISH_LANG

## localization part
## get version
_bashish_module sys/version

## get localisation from enviroment
test "$LANG"&&BASHISH_LANG=$LANG

## qnx compatibility
test "$ABLANG"&&BASHISH_LANG=$ABLANG

## if translation for your language is incomplete
## bashish will default to english translation by default
_bashish_module locale/en

## load local translation
_bashish_module locale/$BASHISH_LANG
