#!/bin/bash
##################################################################################
## Bashish, a console theme engine
## Copyright (C) 2010 Thomas Eriksson
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
##################################################################################

function _bashish_appdb
{
	local APP
	
	for APP in "$HOME"/.bashish/launcher/*
	do
		test -d "${HOME}"/.bashish/app/"${APP##*/}"||rm "${APP}" 2>/dev/null
	done
	
	for APP in "$HOME"/.bashish/app/*
	do
		test -L "${HOME}/.bashish/launcher/${APP##*/}"||ln -sf "${BASHISHDIR}"/lib/_bashish_launcher "${HOME}"/.bashish/launcher/${APP##*/}
	done
}
_bashish_appdb
