#!/bin/bash
##################################################################################
## Bashish, a console theme engine
## Copyright (C) 2005 Thomas Eriksson
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
##################################################################################
## autohandler() sets the following variables
## $AUTOSHELL subdir to which specific autoload file is located in
## $AUTORC initialization file where the autoload code should be added/removed from
function autohandler
{
	AUTOSHELL=${1##*=}
	case "$AUTOSHELL" in
	fish)AUTORC="$HOME/.fish";;
	bash)
		AUTORC="$HOME/.bashrc"
		AUTOSHELL=sh
	;;
	zsh)AUTORC="$HOME/.zshrc";AUTOSHELL=sh;;
	dash|ash|sh|ksh|pdksh|mksh)
		AUTORC="$HOME/.profile"
		test -f "$ENV" && AUTORC="${ENV}"
		AUTOSHELL=sh
	;;
	rc)AUTORC="$HOME/.rcrc";;
	es)AUTORC="$HOME/.esrc";AUTOSHELL=rc;;
	csh)AUTORC="$HOME/.cshrc";;
	tcsh)AUTORC="$HOME/.tcshrc";AUTOSHELL=csh;;
	lsh)AUTORC="$HOME/.autoexec";AUTOSHELL=dos;;
	osh)AUTORC="$HOME/.oshrc";AUTOSHELL=osh;;
	esh)AUTORC="$HOME/.eshrc";AUTOSHELL=esh;;
	*)errorhandler 2;;
	esac
}
