#!/bin/bash
##################################################################################
## Bashish, a console theme engine
## Copyright (C) 2005 Thomas Eriksson
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
##################################################################################
##
## this is the interface to the user when the 'bashish' command is
## issued, if no arguments are given, a bashish session will start
##
## the bashish command has quite some options which are parsed here
##
###############################################################################


IFS="[]"
for LIST in $(gconftool-2 --get /apps/gnome-terminal/global/profile_list 2>/dev/null);do :;done
case "$LIST" in
*,Bashish|Bashish,*|*,Bashish,*)
	:
;;
*)

	## translate template to schema
	sed s/SCHEMANAME/Bashish/g $BASHISHDIR/main/terminal/templates/gnome-terminal/schema >$HOME/.bashish/tmp/Bashish
	## load schema

	gconftool-2 --load $HOME/.bashish/tmp/Bashish
	gconftool-2 --type string --set /apps/gnome-terminal/global/default_profile "Bashish"
	gconftool-2 --type list --list-type=string --set /apps/gnome-terminal/global/profile_list "[${LIST},Bashish]"
	
	## cleanup
	rm $HOME/.bashish/tmp/Bashish
	echo "bashish: a gnome-terminal configuration profile has been installed to let bashish control gnome-terminal.
bashish: if you do not wish to let bashish handle the theming of gnome-terminal, change the option \"Profile used when launching a new terminal:\" to Default, or uninstall Bashish.

bashish: please close all gnome-terminal tabs and windows and restart gnome-terminal to restart bashish."
read -n1
"")
esac
unset IFS
