#!/bin/bash
##################################################################################
## Bashish, a console theme engine
## Copyright (C) 2010 Thomas Eriksson
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
##################################################################################
##
## bashish provides mechanisms for changing themes.
## it is loaded by the bashish command
##
###############################################################################

parseopts ()
{
	case "${CMD}" in
	*fg|*fgcolor)	FGCOLOR="${ARG}";;
	*bg|*bgcolor)	BGCOLOR="${ARG}";;
	*fn|*fontname)	FONTNAME="${ARG}";;
	*fs|*fontsize)	FONTSIZE="${ARG}";;
	*tr|*transparency) TRANSPARENCY="${ARG}":;;
	*sh|*shade)		SHADE="${ARG}";;
	*fn|*fontname)	FONTNAME="${ARG}";;
	*xf|*xfont)		XFONT="${ARG}";;
	*lf|*lfont)		LFONT="${ARG}";;
	*bd|*bold)		BOLDCOLOR="${ARG}";;
	esac
}

test -f "${HOME}/.bashish/defaults/theme.user" && . "${HOME}/.bashish/defaults/theme.user"

test -f "${HOME}/.bashish/overrides/theme.user" && . "${HOME}/.bashish/overrides/theme.user"
