#!/bin/bash
##################################################################################
## Bashish, a console theme engine
## Copyright (C) 2010 Thomas Eriksson
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
##################################################################################

## update all terminals, by removing the sync file - which tells bashish
## it is updated to latest enviroment since last time bashishtheme were run
##
## send a WINCH which gets trapped by the interactive shell, and
## promptupdate() is run (only bourne, korn and posix shells)
function _bashish_update
{
	rm "$HOME"/.bashish/tmp/*/sync 2>/dev/null
	for SHPIDFILE in "$HOME"/.bashish/tmp/*/shpid*
	do
		case "$SHPIDFILE" in
		*/\*/shpid*) return 0;;
		esac
		if test -f "${SHPIDFILE}"
		then
			read SHPID <"$SHPIDFILE"
			kill -s WINCH "$SHPID" 2>/dev/null
		fi
	done
}
_bashish_update
