#!/bin/bash
##################################################################################
## Bashish, a console theme engine
## Copyright (C) 2010 Thomas Eriksson
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
##################################################################################
function _bashish_xterm_ansi
{
	## check if the ansi colors need updating
	## change the 16 ansi colors
	n=0
	while test $n -lt 15
	do
		test "x${BASHISH_STATE[$n]}" != "x${COLOR[$n]}" && {
			BASHISH_BULKVAR="$BASHISH_BULKVAR\033]4;$n;${COLOR[$n]}\007"
			BASHISH_STATE[$n]="${COLOR[$n]}"
		}
		let n++
	done
}
