#!/bin/bash
##################################################################################
## Bashish, a console theme engine
## Copyright (C) 2010 Thomas Eriksson
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
##################################################################################
##
## this code section contains title setting code for the legacy 
## Sun cmdtool and shelltool terminals part of NeWS and Open Windows for
## SunOS/Solaris
##
##################################################################################
function _bashish_cmdtool_printtitle
{
	## OpenWindows shelltool / cmdtool title
	BASHISH_BULKVAR="$BASHISH_BULKVAR\033]l"$TITLE"\033\\\\\033]L"$ICON"\033\\\\\017"
}
