#!/bin/bash
##################################################################################
## Bashish, a console theme engine
## Copyright (C) 2010 Thomas Eriksson
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
##################################################################################

function _bashish_rxvt_color
{
	## set foreground and background color
	## set foreground and background color
	test "x${BASHISH_STATE[299]}" != "x$FGCOLOR$BGCOLOR$CURSORCOLOR$FGMOUSECOLOR$BGMOUSECOLOR"&&{
		BASHISH_STATE[299]="$FGCOLOR$BGCOLOR$CURSORCOLOR$FGMOUSECOLOR$BGMOUSECOLOR"

		BASHISH_BULKVAR="$BASHISH_BULKVAR\
\033]12;$CURSORCOLOR\007\
\033]13;$FGMOUSECOLOR\007\
\033]14;$BGMOUSECOLOR\007\
\033]17;$UNDERLINECOLOR\007\
\033]18;$BOLDCOLOR\007\
\033]39;$FGCOLOR\007"

		test "x$IMAGEFILE" = x && BASHISH_BULKVAR="$BASHISH_BULKVAR\033]49;$BGCOLOR\007"
	}
}
