#!/bin/bash
##################################################################################
## Bashish, a console theme engine
## Copyright (C) 2010 Thomas Eriksson
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
##################################################################################
function _bashish_rxvt_image
{
	## background image, reset if none is specified
	if test "${BASHISH_STATE[300]}" != "${IMAGEFILE};${IMAGESCALE}"
	then
		test "x$IMAGESCALE" != x && local IMAGESCALE=";$IMAGESCALE"
		## Eterm must have a nonsense file name in order to remove the image
		if test "x$IMAGEFILE" != x
		then
			BASHISH_BULKVAR=$BASHISH_BULKVAR"\033]20;`_bashish_whichbtdir $IMAGEFILE`$IMAGEFILE$IMAGESCALE\007"
		else
			BASHISH_BULKVAR=$BASHISH_BULKVAR"\033]20;\007"
		fi
		BASHISH_STATE[300]="${IMAGEFILE}${IMAGESCALE}"
	fi
}

