#!/bin/bash
##################################################################################
## Bashish, a console theme engine
## Copyright (C) 2010 Thomas Eriksson
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
##################################################################################

## at some unlucky events the TCSETSW ioctl call would be interrupted by a
## SIGWINCH signal and the keyboard would be messed up
##
## Bashish triggers this bug quite often since it changes the size when 
## a program is started.
##
function _bashish_gnome-terminal_winch
{
	## do not activate gnome theming if in app theming mode
	## if enabled, this would affect all terminals,
	## I have not found an automatic workaround for this, 
	## only manually specifying a profile for each tty which is quite annoying
	case "$BTDIR" in
	*/prompt/|*/prompt)
	:
	;;
	*)
		## $LAUNCHER PID isnt updated when running child shells and then exiting
		kill -s WINCH $LAUNCHER_PID 2>/dev/null
		return 0
	esac
	test "x${FONTNAME}${FONTSIZE}" = "x${BASHISH_STATE[401]}${BASHISH_STATE[402]}" && kill -s WINCH $LAUNCHER_PID 2>/dev/null
}
