#!/bin/bash
##################################################################################
## Bashish, a console theme engine
## Copyright (C) 2010 Thomas Eriksson
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
##################################################################################
function _bashish_eterm_ansi
{
	## check if the ansi colors need updating
	## change the 16 ansi colors
	## 
	## Older versions of Eterm only supported the Linux color sequence to change colors
	local i=0 h
	for h in 0 1 2 3 4 5 6 7 8 9 a b c d e f
	do
		if test "$i" -gt 9
		then
			let i++
		else
			i=h
		fi
		test "x${BASHISH_STATE[$i]}" != "x${COLOR[$i]}" && {
			BASHISH_BULKVAR="$BASHISH_BULKVAR\033]P$h${COLOR[$i]###}"
			BASHISH_STATE[$i]="${COLOR[$n]}"
		}
	done
}
