#!/usr/bin/fish
##################################################################################
## Bashish, a console theme engine
## Copyright (C) 2010 Thomas Eriksson
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
##################################################################################
##
## THIS IS BASHISH2. YOU WILL BE ASSIMILATED
##
######################################################

## _bashish_module is a function that reads and executes shell script 
## parts located in $BASHISHDIR/modules/sh/
function _bashish_module
	. "$BASHISHDIR"/modules/sh/$1
end

## changetheme function
function changetheme
	(which changetheme) $1 $2 $3
        _bashish_module sys/loadprompt
end

## load the theme engine
_bashish_module sys/loadprompt
