#!/bin/bash
##################################################################################
## Bashish, a console theme engine
## Copyright (C) 2005 Thomas Eriksson
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
##################################################################################
##
## provides:
## _bashish_find()
##
## usage:
## _bashish_find [THEME]
## 
## sets global variable THEMENAME with full path and filename to selected theme
## returns 1 if given THEME could not be found, no THEMENAME will be set
##
###############################################################################
function _bashish_find
{
	typeset n=0
	while test "x${THEME_LIST[$n]}" != x
	do
		if test 	x"${THEME_LIST[$n]##*/}" = "x${1}" \
	 			-a -f "${THEME_LIST[$n]}"/theme
		then
			THEME=${1};\
			THEME=${THEME##*/};\
			THEMEFILE=${THEME_LIST[$n]};\
			return 0; \
		fi
		let n++
	done
	return 1
}
